# 总结一下numpy中所有有关与改变array形状的操作
- reshape   ---   resize  # 改变形状
- 元祖
- expand_dim   # 增加一个轴
- np.newaxis   # 增加一个轴

- ravel   ---   flatten  # 展平
- squeeze -- 压缩维度为一的轴
- transpose  # 转置

In [3]:
import numpy as np

In [35]:
a = np.arange(12)
a.shape   # 1 维

(12,)

In [36]:
# 第一种 reshape

# 不管列数，行位为3
a.reshape(3,-1)   # 3维
a.reshape(12, 1) # 2 维
a.reshape(12,1,1) # 3 维

array([[[ 0]],

       [[ 1]],

       [[ 2]],

       [[ 3]],

       [[ 4]],

       [[ 5]],

       [[ 6]],

       [[ 7]],

       [[ 8]],

       [[ 9]],

       [[10]],

       [[11]]])

In [37]:
# 如果需要在数组上增加维度,输入需要增添维度的轴即可
# axis=0代表扩展列, axis=-1代表扩展最后一个参数
a_add_dimension = np.expand_dims(a,axis=0)
print(a_add_dimension.shape)   # 2 维

a_add_dimension = np.expand_dims(a,axis=1)
print(a_add_dimension.shape)   # 2 维

a_add_dimension = np.expand_dims(a,axis=-1)
print(a_add_dimension.shape)   # 2 维

# 不管列数，行位为3
a_add_dimension = a.reshape(3,-1)   # 3维
a_add_dimension = np.expand_dims(a_add_dimension,axis=1)
print(a_add_dimension.shape)

(1, 12)
(12, 1)
(12, 1)
(3, 1, 4)


In [38]:
a_new = a[:,np.newaxis]
a_new.shape

(12, 1)

In [39]:
a_new = a[np.newaxis, :]
a_new.shape

(1, 12)

In [40]:
a = np.arange(12).reshape(3,4)
a.ravel().shape  # 

(12,)

In [41]:
# flatten函数 也是将多维数组展平，与ravel函数的功能相同，
# 不过flatten函数会请求分配内存来保存结果，而ravel函数只是返回数组的一个视图(view)
a = np.arange(12).reshape(3,4)
a.flatten().shape  # 

(12,)

In [5]:
a = np.arange(12).reshape(3,4)
a.shape = (3,4)
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [7]:
a = np.arange(12).reshape(3,4)
d = a.transpose()   # 转置
print(d)

[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [12]:
# resize函数 和reshape函数的功能一样，但resize会直接修改所操作的数组
a = np.arange(12).reshape(3,4)
a.resize((12,))
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [15]:
# 压缩维度移除轴，默认压缩所有为1的维度
a = np.arange(12).reshape(3,4,1,1,1)
b = a.squeeze()
b.shape

(3, 4)

In [18]:
# 只压缩某一个维度为一的轴
a = np.arange(12).reshape(3,4,1,1,1)
b = a.squeeze(axis=2)
b.shape

(3, 4, 1, 1)

# tensorflow常用的张量tensor操作的总结
- tf.concat(data,concat_dim)  # 连接
- tf.squeeze(input, squeeze_dims=None, name=None)  # 降维
- tf.expand_dims(input, axis=None, name=None, dim=None)  # 升维
- tf.pad(
    tensor,
    paddings,
    mode='CONSTANT',
    name=None,
    constant_values=0
)   # 在某个轴的周围增加0

In [19]:
import tensorflow as tf

In [21]:
# data:[d1,d2..]是一个列表，把d1,d2..的数据按照concat_dim合并起来，不增加也不减少维度
# 合并的前提是：这些数据除了concat_dim这一个维度外，其他维度都要完全相等才可以。

t1=tf.ones([2,2,3])
t2=tf.zeros([2,3,3])
t3=tf.ones([2,1,3])

a=tf.concat([t1, t2,t3],1)  # 在1维拼接
a.shape

TensorShape([2, 6, 3])

In [35]:
# 这个是一个降维操作，当squeeze_dims=None时，会把所有大小是1的维度，删除。当squeeze_dims不为空时，删除相应axis对应的维度（但这个axis的大小必须为1，否则会报错。）

# 与numpy相同
a = tf.ones([3, 4, 1])
print(a)
b = tf.squeeze(a)
b

tf.Tensor(
[[[1.]
  [1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]
  [1.]]], shape=(3, 4, 1), dtype=float32)


<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)>

In [43]:
# 在axis位置，增加一个大小为1的维度
# 这个在做广播时非常有用，比如想让维度是[2,3,4,2]和[3,4]的张量相加，由于维度不匹配，没有办法广播。[3,4]应该扩充维度至[1,3,4,1]。

t1 = tf.ones([3,4])
t2 = tf.ones([2,3,4,2])

t1 = tf.expand_dims(t1, axis=0)  # 只能一个一个加
print(t3)
t1 = tf.expand_dims(t1, axis=3)
print(t3)
t = t1 + t2
t

tf.Tensor(
[[[[1.]
   [1.]
   [1.]
   [1.]]

  [[1.]
   [1.]
   [1.]
   [1.]]

  [[1.]
   [1.]
   [1.]
   [1.]]]], shape=(1, 3, 4, 1), dtype=float32)
tf.Tensor(
[[[[1.]
   [1.]
   [1.]
   [1.]]

  [[1.]
   [1.]
   [1.]
   [1.]]

  [[1.]
   [1.]
   [1.]
   [1.]]]], shape=(1, 3, 4, 1), dtype=float32)


<tf.Tensor: shape=(2, 3, 4, 2), dtype=float32, numpy=
array([[[[2., 2.],
         [2., 2.],
         [2., 2.],
         [2., 2.]],

        [[2., 2.],
         [2., 2.],
         [2., 2.],
         [2., 2.]],

        [[2., 2.],
         [2., 2.],
         [2., 2.],
         [2., 2.]]],


       [[[2., 2.],
         [2., 2.],
         [2., 2.],
         [2., 2.]],

        [[2., 2.],
         [2., 2.],
         [2., 2.],
         [2., 2.]],

        [[2., 2.],
         [2., 2.],
         [2., 2.],
         [2., 2.]]]], dtype=float32)>

In [26]:
# 对一个一维向量padding时，padding = [[U, D]],其中U头填充的个数，D为尾填充的个数。
t1 = tf.ones(12)
tf.pad(t1, [[1,1]])  # 后面必须是二维的

<tf.Tensor: shape=(14,), dtype=float32, numpy=
array([0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
      dtype=float32)>